name: Deploy Demo to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 代码质量检查
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run linting
      run: npm run check

    - name: Build library (test)
      run: npm run build

  # 构建和部署
  build-and-deploy:
    runs-on: ubuntu-latest
    needs: lint-and-test

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build library
      run: npm run build

    - name: Install demo dependencies
      run: |
        cd demo
        npm ci

    - name: Build demo for production
      run: |
        cd demo
        NODE_ENV=production npm run build

    - name: Create 404.html for SPA routing
      run: |
        cp demo/dist/index.html demo/dist/404.html

    - name: Add .nojekyll file
      run: |
        touch demo/dist/.nojekyll

    - name: Setup Pages
      uses: actions/configure-pages@v4
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      with:
        path: './demo/dist'

  # 部署到 GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
